name: Run PowerShell Script with Arguments

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    container:
      image: alpine
      options: --entrypoint "sh"

    steps:
    - name: List
      run: uname -a
