name: Auto Version Bump

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Read JSON file
        run: |
          contents=$(<./.version)
          major=$(node -e "console.log(JSON.parse('$contents').version.major)")
          major=$(node -e "console.log(JSON.parse('$contents').version.minor)")
          major=$(node -e "console.log(JSON.parse('$contents').version.build)")
          major=$(node -e "console.log(JSON.parse('$contents').version.revision)")
          echo "Major: $major"
          echo "Major: $minor"
          echo "Major: $build"
          echo "Major: $revision"

      # - name: Build and push Docker image
      #   run: |
      #     docker build -t your-image-name:${{ steps.increment_version.outputs.new_version }} .
      #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ github.actor }}" --password-stdin
      #     docker push your-image-name:${{ steps.increment_version.outputs.new_version }}
