name: Release

on:
  push:
    - dev

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{secrets.DOCKER_PASSWORD}}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Read JSON file
        run: |
          contents=$(<version.json)
          version_bump=$(echo "$contents" | jq '.version.revision += 1')
          echo "$version_bump" > version.json

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.json
          git commit -m "Revision bump"
          git push

      # - name: Build and push Docker image
      #   run: |
      #     docker build -t your-image-name:${{ steps.increment_version.outputs.new_version }} .
      #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ github.actor }}" --password-stdin
      #     docker push your-image-name:${{ steps.increment_version.outputs.new_version }}
