name: Print Current Branch

on:
  push:
    branches:
      - dev
      - main
      - test

jobs:
  print-branch-job-1:
    runs-on: ubuntu-latest

    if: github.ref != 'refs/heads/main'
    steps:
      - name: Print Current Branch
        run: echo "Current branch: ${{github.ref}}"
