name: Print Current Branch

on:
  push:
    branches:
      - '*'
    branches-ignore: 
      - main

jobs:
  print-branch-job-1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Current Branch
        run: echo "Current branch"
