name: Print Current Branch

on:
  push:
    branches:
      - '*'

jobs:
  print-branch-job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Print branch
        run: |
          echo ${{steps.extract_branch.outputs.branch}}
              
