name: Run PowerShell Script with Arguments

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest


    steps:
    - name: List1
      run: |
        echo "PR Branch Name: ${{ github.head_ref }}"
