name: Merge to dev

on:
  pull_request:
    types: [closed]

jobs:
  revision_bump:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: dev
          token: ${{secrets.DOCKER_PASSWORD}}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Bump the revision
        run: |
          current_branch=${{github.ref}}
          contents=$(<version.json)
          version_bump=$(echo "$contents" | jq '.version.revision += 1')
          echo "$version_bump" > version.json
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.json
          git commit -m "Revision bump"
          git push

  build:
    needs: revision_bump
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: dev
          token: ${{secrets.DOCKER_PASSWORD}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
            
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          contents=$(<version.json)
          major=$(echo "$contents" | jq -r '.version.major')
          minor=$(echo "$contents" | jq -r '.version.minor')
          build=$(echo "$contents" | jq -r '.version.build')
          revision=$(echo "$contents" | jq -r '.version.revision')

          version="$major.$minor.$build.$revision"

          docker buildx build \
          --platform arm64 \
          --build-arg ver=$version \
          --push \
          -t ghcr.io/abhimanyukk-druck-utthunga/workflowtest:$version .
